# Project: Mystring
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = match_test.o mystring.o string_test.o
LINKOBJ  = match_test.o mystring.o string_test.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -mwindows
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/E470/Desktop/·/数据结构/实验二20191012/2-3_patternMatch" -I"C:/Users/E470/Desktop/·/数据结构/实验二20191012/2-3_patternMatch"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/Users/E470/Desktop/·/数据结构/实验二20191012/2-3_patternMatch" -I"C:/Users/E470/Desktop/·/数据结构/实验二20191012/2-3_patternMatch"
BIN      = Mystring.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

match_test.o: match_test.cpp
	$(CPP) -c match_test.cpp -o match_test.o $(CXXFLAGS)

mystring.o: mystring.cpp
	$(CPP) -c mystring.cpp -o mystring.o $(CXXFLAGS)

string_test.o: string_test.cpp
	$(CPP) -c string_test.cpp -o string_test.o $(CXXFLAGS)
